// packages/solid/button/src/button.tsx
import * as pressable from '@zag-js/pressable'
import { normalizeProps, useMachine } from '@zag-js/solid'
import { createMemo, createUniqueId, Component, JSX } from 'solid-js'

import { button as buttonStyles, ButtonStyleProps } from '@pulse-ui/button'

export interface ButtonProps
  extends ButtonStyleProps,
    Omit<pressable.Context, 'id'> {
  id?: string
  children?: JSX.Element
}

export const Button: Component<ButtonProps> = (props) => {
  const { children, id, onPress, onLongPress } = props

  const [state, send] = useMachine(
    pressable.machine({
      id: id || createUniqueId(),
      onPress,
      onLongPress,
    })
  )

  const api = createMemo(() => pressable.connect(state, send, normalizeProps))

  return (
    <button {...api().pressableProps} class={buttonStyles(props)}>
      {children}
    </button>
  )
}

// packages/react/button/src/button.tsx
import * as React from 'react'
import * as pressable from '@zag-js/pressable'
import { useMachine, normalizeProps } from '@zag-js/react'

import { button, ButtonStyleProps } from '@pulse-ui/button'

export interface ButtonProps
  extends ButtonStyleProps,
    Omit<pressable.Context, 'id'> {
  id?: string
  children?: React.ReactNode
}

export const Button: React.FC<ButtonProps> = (props) => {
  const { children, id, onPress, onLongPress } = props

  const [state, send] = useMachine(
    pressable.machine({
      id: id || React.useId(),
      onPress,
      onLongPress,
    })
  )

  const api = pressable.connect(state, send, normalizeProps)

  return (
    <button {...api.pressableProps} className={button(props)}>
      {children}
    </button>
  )
}
